apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql-app
spec:
  volumes:
    - name: mysql-pv-pod
      persistentVolumeClaim:
       claimName: mysql-pvc
  containers:
    - name: mysql
      image: mysql
      imagePullPolicy: IfNotPresent
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "admin"
      resources:
        limits: 
          cpu: 500m
          memory: 2048Mi
        requests:
          cpu: 200m
          memory: 1024Mi
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-pv-pod
          mountPath: /var/lib/mysql
