apiVersion: v1
kind: ReplicationController
metadata:
 name: mysql-rc
 labels:
  app: mysql-rc
spec:
 replicas: 1
 selector:
  name: mysql-app
 template:
  metadata:
   name: mysql-pod
   labels:
    name: mysql-app
  spec:
   volumes:
    - name: mysql-pv-pod
      persistentVolumeClaim:
       claimName: mysql-pvc
   containers:
    - name: mysql
      image: mysql
      imagePullPolicy: IfNotPresent
      env:
       - name: MYSQL_ROOT_PASSWORD
         value: admin
      ports:
       - containerPort: 3306
      volumeMounts:
       - name: mysql-pv-pod
         mountPath: /var/lib/mysql
