---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heketi-service-account
  labels:
    glusterfs: heketi-sa
    heketi: sa
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: heketi
  labels:
    k8s-app: heketi-role
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete","exec"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: heketi
  labels:
    k8s-app: heketi-rolebind
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: heketi-service-account
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: heketi
  apiGroup: ""
