kind: ReplicationController
apiVersion: v1
metadata:
 name: neo4j-rc
 labels:
  type: cs-rc
spec:
 replicas: 2
 selector:
  name: neo4j-init-cs
 template:
  metadata:
   labels:
    name: neo4j-init-cs
    app: neo4j
  spec:
   hostNetwork: true
   nodeSelector:
     neo4j: correct
   volumes:
    - name: "volume-cluster"
      persistentVolumeClaim:
       claimName: neo4j-pvc
   containers:
    - name: neo4j
      image: 172.19.0.131:5000/neo4j:enterprise
      imagePullPolicy: IfNotPresent
      ports:
       - containerPort: 7474
       - containerPort: 7473
       - containerPort: 7687
       - containerPort: 5000
       - containerPort: 6000
       - containerPort: 7000
      env:
       - name: NEO4J_dbms_mode
         value: "CORE"
       - name: NEO4J_causal__clustering_expected__core__cluster__size
         value: "2"
       - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
         value: "yes"
      volumeMounts:
       - name: "volume-cluster"
         mountPath: "/initdir"
