kind: ReplicationController
apiVersion: v1
metadata:
 name: neo4j-cs-rc
spec:
 replicas: 1
 selector:
  name: neo4j-cs
 template:
  metadata:
   name: neo4j-cs
   labels:
    name: neo4j-cs
    app: neo4j
  spec:
   hostNetwork: true
   volumes:
    - name: volume-cluster
      hostPath:
       path: /home/yanghang/initdir
   nodeSelector:
    neo_name: node4
   containers:
    - name: neo4j-cs
      image: nwpuyh/neo4j:enterprise
      imagePullPolicy: IfNotPresent
      ports:
       - containerPort: 7474
       - containerPort: 7473
       - containerPort: 7687
       - containerPort: 5000
       - containerPort: 6000
       - containerPort: 7000
      env:
       - name: MY_NEO4J_INIT_MEMBER_LIST
         value: "2"
       - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
         value: "yes"
       - name: NEO4J_dbms_mode
         value: "CORE"
      volumeMounts:
       - name: volume-cluster
         mountPath: /initdir
