kind: ReplicationController
apiVersion: v1
metadata:
 name: neo4j-rc
 labels:
  type: cs-rc
spec:
 replicas: 2
 selector:
  app: neo4j
 template:
  metadata:
   name: neo4j-test
   labels:
    app: neo4j
  spec:
   nodeSelector:
    neo_name: node4
   containers:
    - name: neo4j
      image: ilmare/neo4j:enterprise
      imagePullPolicy: Never
      ports:
       - containerPort: 7474
       - containerPort: 7473
       - containerPort: 7687
       - containerPort: 5000
       - containerPort: 6000
       - containerPort: 7000
      env:
       - name: NEO4J_dbms_mode
         value: "CORE"
       - name: NEO4J_causal__clustering_expected__core__cluster__size
         value: "1"
       - name: NEO4J_causal__clustering_initial__discovery__members
         value: "10.244.202.22:5000,10.244.202.21:5000"
       - name: NEO4J_causal__clustering_discovery__advertised__address
         value: "localhost:5000"
       - name: NEO4J_causal__clustering_transaction__advertised__address
         value: "localhost:6000"
       - name: NEO4J_causal__clustering_raft__advertised__address
         value: "localhost:7000"
       - name: NEO4J_dbms_connectors_default__advertised__address
         value: "localhost"
       - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
         value: "yes"
