kind: Pod
apiVersion: v1
metadata:
 name: neo4j-2
 labels:
  type: read-replica-slave
  app: neo4j
spec:
 nodeSelector:
  neo_name: node2
 containers:
  - name: neo4j
    image: neo4j:enterprise
    imagePullPolicy: IfNotPresent
    ports:
     - containerPort: 7474
     - containerPort: 7473
     - containerPort: 7687
     - containerPort: 5000
     - containerPort: 6000
     - containerPort: 7000
    env:
     - name: NEO4J_dbms_mode
       value: "READ_REPLICA"
     - name: NEO4J_causal__clustering_initial__discovery__members
       value: "172.19.0.134:5000,172.19.0.133:5000"
     - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
       value: "yes"
